### ISSUE TITLE
Add a new general SSH operation

### ISSUE THREAD

**Issue by oritstone** [openscore/slang-content#1]
The operation should be a .sl file
Should be under: org\openscore\slang\technologies\remote_command_execution\SSH
With namespace: org.openscore.slang.technologies.remote_command_execution.SSH

@orius123 @meirwah @meshipeer - better suggestions on the exact location/name of folders? 
I took it from OO 9.x repository

**Comment by avimora** [comment]
I suggest using shorter & all lowercase namespace

**Comment by meirwah** [comment]
i think "base" instead of  "technologies" .. i agree with lower case...

**Comment by oritstone** [comment]
So let's go with: 
org\openscore\slang\base\remote_command_execution\ssh

**Comment by meirwah** [comment]
please look at @TudorLesanHP  branch before working on this... (maybe even better to work on his branch)

**Comment by Bonczidai** [comment]
added the operation in Tudor's branch, please review

**Comment by meirwah** [comment]
can you link the pull request to this issue?

**Comment by Bonczidai** [comment]
I referenced the issue in the commit message; once merged into the master branch it should close this issue
