### ISSUE TITLE
Input/Output convention question.

### ISSUE THREAD

**Issue by TudorLesanHP** [openscore/slang-content#14]
@oritstone The inputs/outpus should respect the convention of word separated by underscore. But my question is, what should I do about the inputs of actions implemented by content like SSH,HttpClient, SendEmail etc. Those have inputs with camelcase. It seems we should either change the content aswell or change the convention back to camelcase. Any suggestions?

**Comment by orius123** [comment]
Hi,

the underscore convention comes from python,
there are people that write camelCase for variables in python but most doesn't..
so, moving to camel case will be better for Java, but since I believe most of our content will use python personally I prefer underscores.

vote?

**Comment by meirwah** [comment]
i think all can agree on the underscore convention, BUT issue is what we do with inputs of the actions(which are java based)??

**Comment by orius123** [comment]
why not making operations that are `java` based use `camelCase' and `Python` based use underscores?

#Java op
```yaml
- java_op
    inputs:
      - firstInput
      - secondInput
    ....
```
#Python op
```yaml
- python_op
    inputs:
      - first_input
      - second_input
    ....
```

**Comment by meirwah** [comment]
:+1: from my prespective...

**Comment by oritstone** [comment]
:+1:

**Comment by TudorLesanHP** [comment]
@orius123 @meirwah @oritstone there is one problem with this approach. Let's say we have a flow that has 2 steps that have as outputs error messages and an on_failure step which sends the error message as an email. If for example the first step will be a python_op then it would have the output error_message and the other one if it's a java_op it would have the output errorMessage. That means that everytime I have to check which one is not empty and email that one. The same for returnResult.Sounds good? WDYT?

**Comment by oritstone** [comment]
The problem with the different conventions between python & Java actions is only relevant in the operations, and each operation should be in a separate file.
When you specify an output to the operation, you can give whatever name you want, and it should be by our lower case words convention:
```
- java_op
    inputs:
      - firstInput
      - secondInput
    outputs:
      - error_message: errorMessage
```
And then in the flow, all the tasks deal with lower case names

**Comment by TudorLesanHP** [comment]
:+1:

**Comment by orius123** [comment]
feel free to close if you think it is resolved :smiley:
