### ISSUE TITLE
'less_than_percentage.sl' is not working properly

### ISSUE THREAD

**Issue by Asisayag** [openscore/slang-content#16]
I wrote a flow using this operation, and encounter an issue. 
For inputs:first = 10, second = 20. it worked fine. 
For inputs:first = 300, second = 20. it worked fine. 
However, for inputs:first = 100, second = 20. it said that the first is smaller, like it compares only the first character.

**Comment by SamMarkowitz** [comment]
It's doing a string comparison. Need to cast.

**Comment by meirwah** [comment]
you're right , @TudorLesanHP please handle this...

**Comment by TudorLesanHP** [comment]
Fixed.

**Comment by meirwah** [comment]
where is the pull request for this fix @TudorLesanHP ?

**Comment by TudorLesanHP** [comment]
@meirwah  did pull request for branch fix_less_than_percentage

**Comment by meirwah** [comment]
nope...

**Comment by orius123** [comment]
someone committed it...
closing.
