### ISSUE TITLE
Need to add section to CONTRIBUTING.md on how to validate the content

### ISSUE THREAD

**Issue by orius123** [openscore/slang-content#19]

**Comment by oritstone** [comment]
I think we need to postpone this until we have the framework for s-unit & for system tests on the content.
@meshipeer @meirwah @orius123 WDYT?

**Comment by meirwah** [comment]
make sense...

**Comment by meshipeer** [comment]
i think we need to add what we have for now and update when we add more requiremnts

**Comment by oritstone** [comment]
Fixed
