### ISSUE TITLE
why the path is org.openscore

### ISSUE THREAD

**Issue by meirwah** [openscore/slang-content#3]
it should be io.openscore

**Comment by meirwah** [comment]
@meshipeer @orius123  @oritstone is this urgent to fix ??

**Comment by orius123** [comment]
I don't think it is.
except to maven central, nobody really cares..

**Comment by meirwah** [comment]
but the flows path might be an issue no?

**Comment by orius123** [comment]
Issue for what? It is not neat, but no functionality supposed to be harmed by the path. AFAIK

**Comment by orius123** [comment]
Issue for what? It is not neat, but no functionality supposed to be harmed by the path. AFAIK

**Comment by orius123** [comment]
Issue for what? It is not neat, but no functionality supposed to be harmed by the path. AFAIK

**Comment by orius123** [comment]
Issue for what? It is not neat, but no functionality supposed to be harmed by the path. AFAIK

**Comment by orius123** [comment]
@meirwah @meshipeer should we close this one?
