### ISSUE TITLE
Content result checks

### ISSUE THREAD

**Issue by tudorlesan** [openscore/slang-content#36]
After an update to score-language I noticed less_than_percentage operation kept throwing this error:

"Command failed java.lang.RuntimeException: Slang Error : Error running: 'less_than_percent
age': No possible result was resolved"

The solution was changing the results to check any output not just strings.
All content must be checked to be sure everything works.

**Comment by oritstone** [comment]
@tudorlesan is it already in progress?

**Comment by tudorlesan** [comment]
@oritstone yes it is
