### ISSUE TITLE
content outputs check

### ISSUE THREAD

**Issue by tudorlesan** [openscore/slang-content#39]
Some of the flows written contain outputs that get their value from an evaluated expression which contains step outputs.
After a score-language update, this error is thrown if the step outputs don't exist
![slangerror](https://cloud.githubusercontent.com/assets/8058958/6482847/458654fa-c273-11e4-811a-5d98e9e83e70.png)

Example:
Flow A contains 2 subflows as steps.
Flow A's output is evaluated from the step outputs of the second subflow.
Flow A gets executed with an input so that step 2 doesn't get executed anymore.
The error is thrown since the flow output can't be evaluated.

**Comment by meirwah** [comment]
adding @orius123  to this thread...
