### ISSUE TITLE
README.md external Python modules

### ISSUE THREAD

**Issue by SamMarkowitz** [openscore/slang-content#51]
@orius123 should I change the instructions for using external python modules here as well? Give all the options?

**Comment by orius123** [comment]
Yes. But just mention that it only if you use the CLI. It is an independent project.

**Comment by SamMarkowitz** [comment]
Good point. 

Follow up question: what would you suggest I do in the comments to flows that use external modules.

Example: jenkins/check_job_exists uses the jenkinsapi module. 

Right now I'm changing it so that after the description it will say:

`Prerequisites: jenkinsapi Python module`

Do you think I need to point them to the readme (or elsewhere) to explain how to use external modules?

**Comment by orius123** [comment]
Sounds good.
